version: '3'

services:
  mariadb:
    image: mariadb:10
    container_name: mariadb
    ports:
      - '3306:3306'
    expose:
      - 3306
    volumes:
      - ./database/conf.d:/etc/mysql/conf.d
      - ./database/data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    env_file: .env
    environment:
      TZ: Asia/Seoul
    networks:
      - default
    restart: always

  redis:
    image: redis:7
    container_name: redis
    environment:
      - REDIS_HOSTS=local:redis:6379
    labels:
      - 'name=redis'
      - 'mode=standalone'
    ports:
      - '6379:6379'
    networks:
      - default

networks:
  default:
